project:
  type: website

website:
  title: "Exam Performance Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: model.qmd
        text: Model
      - about.qmd
      - href: sources.qmd
        text: Sources

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



